### Stage 1: dependency build stage ###
FROM python:3.11-slim AS builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

# Tells uv to compile .pyc bytecode during install.
ENV UV_COMPILE_BYTECODE=1

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-install-project --no-dev


### Stage 2: runtime image ###
FROM python:3.11-slim

WORKDIR /app

# From previous stage we only want its /app/.venv, the output of uv sync
COPY --from=builder /app/.venv /app/.venv
ENV PATH="/app/.venv/bin:%PATH"

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]