services:
  db:
    image: pgvector/pgvector:pg16
    container_name: paprika_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-paprika_ai}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-paprika_ai}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # alloy:
  #   image: grafana/alloy:latest
  #   volumes:
  #     - ./config.alloy:/etc/alloy/config.alloy
  #   command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
  #   ports:
  #     - "12345:12345"
  #   depends_on:
  #     - db

  agent-runtime:
    build:
      context: .
      args:
        - INSTALL_LOCAL=${INSTALL_LOCAL:-false}
    container_name: paprika_agent-runtime
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app # Syncs your code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-paprika_ai}
      REDIS_URL: "redis://redis:6379/0"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  redis_data:
